### ISSUE TITLE
全体のモデル図作成

### ISSUE THREAD

**Issue by skykataoka** [skykataoka/stackoverclone#8]
各モデルのつながりと必要なカラム一覧をまとめた全体像を作成

投票機能がちょっと難しそうですね！

**Comment by yarukigaaru** [comment]
[``](https://www.lucidchart.com/invitations/accept/8b6a520c-fe75-4e29-8707-37984ca660bc)

**Comment by ghost** [comment]
https://www.lucidchart.com/publicSegments/view/5346f9a5-2390-48e8-944c-d44d645bdff0/image.png
